# Generated by Django 3.1.2 on 2020-10-21 22:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201021_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
